### ISSUE TITLE
Convenience module for qualified imports?

### ISSUE THREAD

**Issue by fisx** [cdepillabout/world-peace#6]
Hypothetically, whould you consider accepting a PR for a module `Data.WorldPeace.Qualified` whose export list looks a lot like `Data.WorldPeace` with `openUnion` removed from most names, and possibly some more abbreviations?

This would make code using this library nicer (given the assumption that qualified imports are nice), and it would do very little damage.

Thanks for this library!  Having found this was one of those moments of using Haskell.  :-)

**Comment by cdepillabout** [comment]
@fisx Yeah, this sounds good.

Personally, I don't normally use qualified imports if I can avoid it, but I realize it is a style some people like.

I think we have two choices:

1. Add a module to the `world-peace` package like you're suggesting.  

    However, I'd only consider this option if you'd be willing to become a maintainer for `world-peace` and help keep the `Data.WorldPeace.Qualified` module up-to-date.  I imagine a lot of the documentation would be duplicated between the two modules, so it would be really helpful to have someone in charge of keeping it up to date.

    Also, since `Data.WorldPeace` actually exports both an `OpenUnion` and a `Union` type, we might want to have both `Data.WorldPeace.OpenUnion.Qualified` and `Data.WorldPeace.Union.Qualified`.  Although I think most people will only want to work with `OpenUnion`, so maybe just starting with `Data.WorldPeace.OpenUnion.Qualified` for now.

2. You could create a new package called something like `world-peace-qualified` that just exports a `Data.WorldPeace.OpenUnion.Qualified`.  In this case you would have final say over what the functions are named, etc.  If you add me as a maintainer, then when I add new functionality to the main `Data.WorldPeace` module, I will try to remember to update the `world-peace-qualified` package as well (or at  the very least create an issue on the repo).

    If you decide to go with this approach, then I would still like to make you a maintainer of `world-peace`, so that you could potentially update `world-peace` if you notice anything that should be added when working on `world-peace-qualified`.

    Also, we would have to make sure to add links to `world-peace-qualified` from the main `world-peace` repo.

-----------------------------------------------------------------------------------------------------------

Oh, I guess there is one more possibility.  We could create a `world-peace-qualified` package, but continue to work on it in this repo (using stack or cabal's multi-package repo functionality).  Maybe that would give us the best of both worlds.

**Comment by fisx** [comment]
These are all good plans, my favorite being the worl-peace-qualified package inside this repo.

Annoyingly, I was overly optimistic about my productivity when I opened this and won't have time for this any time soon.  Sorry!

Please decide yourself whether you want to keep this open for somebody else to pick it up, or close it as "won't fix".

**Comment by cdepillabout** [comment]
@fisx Thanks for the update.

I'll close this for now, since I don't have any plans to work on it, and I don't particularly want it.

However, if someone wants to work on this, I can re-open this issue.
